[package]
name = "EventRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventstore = "2.3.0"
serde = "1.0.193"
tokio = { version = "1.35.1", features = ["full"] }
uuid = "1.6.1"
