services:
  eventstore.db:
    image: eventstore/eventstore
    container_name: eventstoredb
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
    ports:
      - "2113:2113"
      - "1113:1113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - RustEventSourcingCQRS

  mongo.db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - RustEventSourcingCQRS

networks:
  RustEventSourcingCQRS:
    driver: bridge


volumes:
  eventstore-volume-data:
  eventstore-volume-logs: